name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t fastapi-app .

      - name: Save Docker image as tar
        run: docker save -o fastapi-app.tar fastapi-app

      - name: Fix permissions for tar file
        run: |
          sudo chown $USER:$USER fastapi-app.tar
          sudo chmod 644 fastapi-app.tar
          ls -l fastapi-app.tar  # Debugging step

      - name: Upload artifact
        uses: actions/upload-artifact@v4  
        with:
          name: fastapi-app
          path: fastapi-app.tar

      - name: Transfer Docker image to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_KEY }}
          port: 22
          source: "fastapi-app.tar"
          target: "/home/${{ secrets.AZURE_VM_USER }}/"

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_KEY }}
          port: 22
          script: |
            set -e  # Exit on any error
            cd /home/${{ secrets.AZURE_VM_USER }}/

            echo "Stopping and removing any existing container..."
            sudo docker stop fastapi-app || true
            sudo docker rm fastapi-app || true

            echo "Removing old Docker image..."
            sudo docker rmi -f fastapi-app || true

            echo "Loading new Docker image..."
            sudo docker load < fastapi-app.tar

            echo "Running new container..."
            sudo docker run -d -p 8000:8000 --name fastapi-app fastapi-app

            echo "Restarting Nginx..."
            sudo systemctl restart nginx

            echo "Deployment complete! 🎉"
